name: Add New API
description: Submit a new API to be added to the registry
title: "[API] "
labels: ["new-api", "needs-review"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing to Public APIs! Please fill out the following information about the API you'd like to add.
        
  - type: input
    id: api-name
    attributes:
      label: API Name
      description: The name of the API
      placeholder: e.g., OpenWeatherMap API
    validations:
      required: true
      
  - type: input
    id: api-url
    attributes:
      label: Base URL
      description: The base URL of the API
      placeholder: e.g., https://api.example.com/v1
    validations:
      required: true
      
  - type: textarea
    id: api-description
    attributes:
      label: Description
      description: A brief description of what the API does
      placeholder: Describe the API's purpose and main features...
    validations:
      required: true
      
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select the most appropriate category
      options:
        - Weather
        - Finance & Markets
        - Health & Medical
        - Education
        - Transportation
        - Entertainment
        - Social Media
        - Maps & Location
        - E-Commerce
        - News & Information
        - Development Tools
        - Communication
    validations:
      required: true
      
  - type: dropdown
    id: auth-type
    attributes:
      label: Authentication Type
      description: What type of authentication does this API require?
      options:
        - none
        - api_key
        - oauth2
        - basic
    validations:
      required: true
      
  - type: dropdown
    id: pricing
    attributes:
      label: Pricing
      description: What is the pricing model?
      options:
        - free
        - freemium
        - paid
    validations:
      required: true
      
  - type: checkboxes
    id: features
    attributes:
      label: Features
      description: Check all that apply
      options:
        - label: Supports CORS
        - label: HTTPS only
        - label: Has rate limiting
        
  - type: input
    id: documentation
    attributes:
      label: Documentation URL
      description: Link to the API documentation
      placeholder: https://docs.example.com/api
    validations:
      required: true
      
  - type: input
    id: tags
    attributes:
      label: Tags
      description: Comma-separated tags for searchability
      placeholder: e.g., weather, forecast, climate
      
  - type: checkboxes
    id: verification
    attributes:
      label: Verification
      description: Please confirm the following
      options:
        - label: I have tested this API and it is working
          required: true
        - label: This API is not already in the registry
          required: true
        - label: The API has public documentation available
          required: true
