import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

// Create apis.json
const apis = {
  apis: [
    {
      id: "openweathermap",
      name: "OpenWeatherMap",
      description: "Current weather, forecasts, and historical data for any location worldwide",
      category: "Weather",
      baseUrl: "https://api.openweathermap.org/data/2.5",
      authType: "api_key",
      cors: true,
      https: true,
      healthStatus: "operational",
      lastChecked: "2025-01-20T14:30:00Z",
      rateLimit: "1,000 calls/day (free)",
      pricing: "freemium",
      documentation: "https://openweathermap.org/api",
      tags: ["weather", "forecast", "climate", "temperature"],
      contributors: { added: "dev-user", lastValidated: "dev-user" },
      responseTime: 120,
      uptime: 99.95
    },
    {
      id: "stripe",
      name: "Stripe",
      description: "Payment processing and billing platform for internet businesses",
      category: "E-Commerce",
      baseUrl: "https://api.stripe.com/v1",
      authType: "api_key",
      cors: false,
      https: true,
      healthStatus: "operational",
      lastChecked: "2025-01-20T14:25:00Z",
      rateLimit: "100 requests/second",
      pricing: "paid",
      documentation: "https://stripe.com/docs/api",
      tags: ["payments", "billing", "subscriptions", "checkout"],
      contributors: { added: "dev-user", lastValidated: "dev-user" },
      responseTime: 150,
      uptime: 99.99
    },
    {
      id: "github",
      name: "GitHub",
      description: "Access GitHub repositories, users, issues, pull requests and more",
      category: "Development Tools",
      baseUrl: "https://api.github.com",
      authType: "oauth2",
      cors: true,
      https: true,
      healthStatus: "operational",
      lastChecked: "2025-01-20T14:20:00Z",
      rateLimit: "5,000 requests/hour",
      pricing: "freemium",
      documentation: "https://docs.github.com/en/rest",
      tags: ["git", "repositories", "developers", "code"],
      contributors: { added: "dev-user", lastValidated: "dev-user" },
      responseTime: 95,
      uptime: 99.97
    },
    {
      id: "restcountries",
      name: "REST Countries",
      description: "Information about countries via a RESTful API",
      category: "Maps & Location",
      baseUrl: "https://restcountries.com/v3.1",
      authType: "none",
      cors: true,
      https: true,
      healthStatus: "operational",
      lastChecked: "2025-01-20T14:15:00Z",
      rateLimit: "Unlimited",
      pricing: "free",
      documentation: "https://restcountries.com/",
      tags: ["countries", "geography", "flags", "population"],
      contributors: { added: "dev-user", lastValidated: "dev-user" },
      responseTime: 85,
      uptime: 99.90
    },
    {
      id: "coingecko",
      name: "CoinGecko",
      description: "Cryptocurrency prices, market data, and exchanges",
      category: "Finance & Markets",
      baseUrl: "https://api.coingecko.com/api/v3",
      authType: "none",
      cors: true,
      https: true,
      healthStatus: "operational",
      lastChecked: "2025-01-20T14:10:00Z",
      rateLimit: "50 calls/minute",
      pricing: "freemium",
      documentation: "https://www.coingecko.com/en/api",
      tags: ["crypto", "bitcoin", "ethereum", "prices"],
      contributors: { added: "dev-user", lastValidated: "dev-user" },
      responseTime: 200,
      uptime: 99.85
    },
    {
      id: "newsapi",
      name: "NewsAPI",
      description: "Search worldwide news articles and headlines from thousands of sources",
      category: "News & Information",
      baseUrl: "https://newsapi.org/v2",
      authType: "api_key",
      cors: false,
      https: true,
      healthStatus: "operational",
      lastChecked: "2025-01-20T14:05:00Z",
      rateLimit: "100 requests/day (free)",
      pricing: "freemium",
      documentation: "https://newsapi.org/docs",
      tags: ["news", "articles", "headlines", "media"],
      contributors: { added: "dev-user", lastValidated: "dev-user" },
      responseTime: 180,
      uptime: 99.80
    },
    {
      id: "spotify",
      name: "Spotify",
      description: "Access music catalog, playlists, user data, and playback controls",
      category: "Entertainment",
      baseUrl: "https://api.spotify.com/v1",
      authType: "oauth2",
      cors: true,
      https: true,
      healthStatus: "operational",
      lastChecked: "2025-01-20T14:00:00Z",
      rateLimit: "Varies by endpoint",
      pricing: "free",
      documentation: "https://developer.spotify.com/documentation/web-api/",
      tags: ["music", "streaming", "playlists", "artists"],
      contributors: { added: "dev-user", lastValidated: "dev-user" },
      responseTime: 140,
      uptime: 99.92
    },
    {
      id: "twilio",
      name: "Twilio",
      description: "Cloud communications platform for SMS, voice, and video",
      category: "Communication",
      baseUrl: "https://api.twilio.com/2010-04-01",
      authType: "api_key",
      cors: false,
      https: true,
      healthStatus: "operational",
      lastChecked: "2025-01-20T13:55:00Z",
      rateLimit: "Varies by plan",
      pricing: "paid",
      documentation: "https://www.twilio.com/docs/usage/api",
      tags: ["sms", "voice", "messaging", "communication"],
      contributors: { added: "dev-user", lastValidated: "dev-user" },
      responseTime: 160,
      uptime: 99.98
    },
    {
      id: "openai",
      name: "OpenAI",
      description: "AI models including GPT-4, DALL-E, and Whisper for text, images, and audio",
      category: "Development Tools",
      baseUrl: "https://api.openai.com/v1",
      authType: "api_key",
      cors: true,
      https: true,
      healthStatus: "operational",
      lastChecked: "2025-01-20T13:50:00Z",
      rateLimit: "Varies by tier",
      pricing: "paid",
      documentation: "https://platform.openai.com/docs",
      tags: ["ai", "gpt", "machine-learning", "chatbot"],
      contributors: { added: "dev-user", lastValidated: "dev-user" },
      responseTime: 350,
      uptime: 99.90
    },
    {
      id: "google-maps",
      name: "Google Maps",
      description: "Maps, geocoding, directions, and places data",
      category: "Maps & Location",
      baseUrl: "https://maps.googleapis.com/maps/api",
      authType: "api_key",
      cors: true,
      https: true,
      healthStatus: "operational",
      lastChecked: "2025-01-20T13:45:00Z",
      rateLimit: "Varies by service",
      pricing: "freemium",
      documentation: "https://developers.google.com/maps/documentation",
      tags: ["maps", "geocoding", "directions", "places"],
      contributors: { added: "dev-user", lastValidated: "dev-user" },
      responseTime: 110,
      uptime: 99.99
    },
    {
      id: "jsonplaceholder",
      name: "JSONPlaceholder",
      description: "Free fake REST API for testing and prototyping",
      category: "Development Tools",
      baseUrl: "https://jsonplaceholder.typicode.com",
      authType: "none",
      cors: true,
      https: true,
      healthStatus: "operational",
      lastChecked: "2025-01-20T13:40:00Z",
      rateLimit: "Unlimited",
      pricing: "free",
      documentation: "https://jsonplaceholder.typicode.com/",
      tags: ["testing", "mock", "fake-api", "development"],
      contributors: { added: "dev-user", lastValidated: "dev-user" },
      responseTime: 50,
      uptime: 99.95
    },
    {
      id: "alpha-vantage",
      name: "Alpha Vantage",
      description: "Stock market data, forex, and cryptocurrency APIs",
      category: "Finance & Markets",
      baseUrl: "https://www.alphavantage.co/query",
      authType: "api_key",
      cors: true,
      https: true,
      healthStatus: "degraded",
      lastChecked: "2025-01-20T13:35:00Z",
      rateLimit: "5 requests/minute (free)",
      pricing: "freemium",
      documentation: "https://www.alphavantage.co/documentation/",
      tags: ["stocks", "forex", "trading", "financial"],
      contributors: { added: "dev-user", lastValidated: "dev-user" },
      responseTime: 450,
      uptime: 98.50
    },
    {
      id: "the-dog-api",
      name: "The Dog API",
      description: "Random dog images and breed information",
      category: "Entertainment",
      baseUrl: "https://api.thedogapi.com/v1",
      authType: "api_key",
      cors: true,
      https: true,
      healthStatus: "operational",
      lastChecked: "2025-01-20T13:30:00Z",
      rateLimit: "10,000 requests/month",
      pricing: "freemium",
      documentation: "https://thedogapi.com/",
      tags: ["dogs", "animals", "images", "pets"],
      contributors: { added: "dev-user", lastValidated: "dev-user" },
      responseTime: 75,
      uptime: 99.88
    },
    {
      id: "pokemon-api",
      name: "PokeAPI",
      description: "All Pokemon data including species, abilities, moves, and games",
      category: "Entertainment",
      baseUrl: "https://pokeapi.co/api/v2",
      authType: "none",
      cors: true,
      https: true,
      healthStatus: "operational",
      lastChecked: "2025-01-20T13:25:00Z",
      rateLimit: "100 requests/minute",
      pricing: "free",
      documentation: "https://pokeapi.co/docs/v2",
      tags: ["pokemon", "games", "anime", "data"],
      contributors: { added: "dev-user", lastValidated: "dev-user" },
      responseTime: 65,
      uptime: 99.92
    },
    {
      id: "nasa",
      name: "NASA APIs",
      description: "NASA data including APOD, Mars Rover photos, and satellite imagery",
      category: "Education",
      baseUrl: "https://api.nasa.gov",
      authType: "api_key",
      cors: true,
      https: true,
      healthStatus: "operational",
      lastChecked: "2025-01-20T13:20:00Z",
      rateLimit: "1,000 requests/hour",
      pricing: "free",
      documentation: "https://api.nasa.gov/",
      tags: ["space", "astronomy", "science", "images"],
      contributors: { added: "dev-user", lastValidated: "dev-user" },
      responseTime: 190,
      uptime: 99.75
    }
  ]
};

fs.writeFileSync(path.join(rootDir, 'data/apis.json'), JSON.stringify(apis, null, 2));
console.log('Created data/apis.json');

// Create categories.json
const categories = {
  categories: [
    { name: "Weather", icon: "cloud", description: "Weather forecasts, historical data, and climate information" },
    { name: "Finance & Markets", icon: "chart", description: "Stock market, cryptocurrency, and financial data" },
    { name: "Health & Medical", icon: "heart", description: "Medical information, drug data, and health services" },
    { name: "Education", icon: "book", description: "Educational resources, courses, and learning materials" },
    { name: "Transportation", icon: "car", description: "Transit, flights, traffic, and vehicle data" },
    { name: "Entertainment", icon: "play", description: "Movies, music, games, and recreational content" },
    { name: "Social Media", icon: "users", description: "Social networks and user-generated content" },
    { name: "Maps & Location", icon: "map", description: "Geolocation, mapping, and geographic data" },
    { name: "E-Commerce", icon: "shopping-cart", description: "Payment processing, products, and retail" },
    { name: "News & Information", icon: "newspaper", description: "News articles, headlines, and media" },
    { name: "Development Tools", icon: "code", description: "Developer utilities, testing, and infrastructure" },
    { name: "Communication", icon: "message", description: "Messaging, email, and voice services" }
  ]
};

fs.writeFileSync(path.join(rootDir, 'data/categories.json'), JSON.stringify(categories, null, 2));
console.log('Created data/categories.json');

console.log('Setup complete!');
